export declare const FUGLE_MARKETDATA_API_REST_BASE_URL: string;
export declare const FUGLE_MARKETDATA_API_VERSION = "v1.0";
export declare const FUGLE_MARKETDATA_API_NORMAL_WEBSOCKET_BASE_URL: string;
export declare const FUGLE_MARKETDATA_API_NORMAL_VERSION = "v1.0";
export declare const FUGLE_MARKETDATA_API_SPEED_WEBSOCKET_BASE_URL: string;
export declare const FUGLE_MARKETDATA_API_SPEED_VERSION = "v1.0";
export declare const CONNECT_EVENT = "connect";
export declare const DISCONNECT_EVENT = "disconnect";
export declare const MESSAGE_EVENT = "message";
export declare const ERROR_EVENT = "error";
export declare const AUTHENTICATED_EVENT = "authenticated";
export declare const UNAUTHENTICATED_EVENT = "unauthenticated";
export declare const UNAUTHENTICATED_MESSAGE = "Invalid authentication credentials";
