"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UNAUTHENTICATED_MESSAGE = exports.UNAUTHENTICATED_EVENT = exports.AUTHENTICATED_EVENT = exports.ERROR_EVENT = exports.MESSAGE_EVENT = exports.DISCONNECT_EVENT = exports.CONNECT_EVENT = exports.FUGLE_MARKETDATA_API_SPEED_VERSION = exports.FUGLE_MARKETDATA_API_SPEED_WEBSOCKET_BASE_URL = exports.FUGLE_MARKETDATA_API_NORMAL_VERSION = exports.FUGLE_MARKETDATA_API_NORMAL_WEBSOCKET_BASE_URL = exports.FUGLE_MARKETDATA_API_VERSION = exports.FUGLE_MARKETDATA_API_REST_BASE_URL = void 0;
const trade_1 = require("../trade");
const fugleRealtime = new trade_1.FugleRealtime();
exports.FUGLE_MARKETDATA_API_REST_BASE_URL = fugleRealtime.realtimeRestUrl;
exports.FUGLE_MARKETDATA_API_VERSION = 'v1.0';
exports.FUGLE_MARKETDATA_API_NORMAL_WEBSOCKET_BASE_URL = fugleRealtime.realtimeWsNormalUrl;
exports.FUGLE_MARKETDATA_API_NORMAL_VERSION = 'v1.0';
exports.FUGLE_MARKETDATA_API_SPEED_WEBSOCKET_BASE_URL = fugleRealtime.realtimeWsSpeedUrl;
exports.FUGLE_MARKETDATA_API_SPEED_VERSION = 'v1.0';
exports.CONNECT_EVENT = 'connect';
exports.DISCONNECT_EVENT = 'disconnect';
exports.MESSAGE_EVENT = 'message';
exports.ERROR_EVENT = 'error';
exports.AUTHENTICATED_EVENT = 'authenticated';
exports.UNAUTHENTICATED_EVENT = 'unauthenticated';
exports.UNAUTHENTICATED_MESSAGE = 'Invalid authentication credentials';
